### Get All Mahasiswa
GET http://localhost:3000/api/mahasiswa

### Add New Mahasiswa
POST http://localhost:3000/api/mahasiswa
Content-Type: application/json

{
  "nim": "20220040280",
  "nama": "Dede Jenal Irawan",
  "gender": "Laki-laki",
  "prodi": "Teknik Informatika",
  "alamat": "Jampang Kulon"
}

### Update Mahasiswa
PUT http://localhost:3000/api/mahasiswa/20220040280
Content-Type: application/json

{
  "nama": "Muhammad Yusuf Mansur",
  "gender": "laki-laki",
  "prodi": "Managemen",
  "alamat": "Sukabumi"
}

### Delete Mahasiswa
DELETE http://localhost:3000/api/mahasiswa/20220040280
